name = "HelpfulErrors"
uuid = "a0d26965-2d43-4500-b796-701bc612d3ff"
authors = ["TEC <tec@tecosaur.com> and contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
